### ISSUE TITLE
Create Github Action

### ISSUE THREAD

**Issue by dmakhun** [Kv-Java-Intensive/course-manager#18]
- build an app on PR/merge into main branch
- configure PRs to not allow merge if a build failed on GA

**Comment by alex-tiutiunnyk** [comment]
I added a .yml file with workflows that build pull request and push into main branch. I also created a badge in README.md with the information about this action. Now it fails :)

**Comment by alex-tiutiunnyk** [comment]
Volodymyr and I fixed some errors in project, so now everything is working
